const catalogProducts = [
	{
		id: "kaiak-clasico",
		name: "Eau de Toilette Kaiak Clásico",
		description: "Una fragancia fresca para acompañar todos tus días.",
		category: "Perfumería",
		subcategory: "Perfumes",
		size: "100 ml",
		price: 34990,
		offerPrice: 24490,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw105510/products/105510_1.jpg",
		featured: true
	},
	{
		id: "aura-alba",
		name: "Eau de Parfum Aura Alba",
		description: "Un aroma envolvente para tus momentos especiales.",
		category: "Perfumería",
		subcategory: "Perfumes",
		size: "75 ml",
		price: 65990,
		offerPrice: 46190,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152254/products/152254_1.jpg",
		featured: false
	},
	{
		id: "tododia-body-splash",
		name: "Body Splash Cereza Negra y Praliné",
		description: "Notas dulces y frutales para refrescar tu rutina.",
		category: "Perfumería",
		subcategory: "Colonias",
		size: "200 ml",
		price: 14790,
		offerPrice: 10350,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152230/products/152230_1.jpg",
		featured: true
	},
	{
		id: "base-cc-cream",
		name: "Base CC Cream Multibeneficios Natura Una",
		description: "Cobertura ligera para un acabado natural y luminoso.",
		category: "Maquillaje",
		subcategory: "Rostro",
		size: "30 ml",
		price: 18990,
		offerPrice: 13290,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152257/products/152257_1.jpg",
		featured: true
	},
	{
		id: "mascara-secret",
		name: "Máscara de Pestañas Secret Natura Una",
		description: "Define y realza tus pestañas con una sola pasada.",
		category: "Maquillaje",
		subcategory: "Ojos",
		size: "8 ml",
		price: 13990,
		offerPrice: 9790,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152259/products/152259_1.jpg",
		featured: false
	},
	{
		id: "labial-matte",
		name: "Labial Matte CC Larga Duración",
		description: "Color intenso y acabado mate para llevar contigo.",
		category: "Maquillaje",
		subcategory: "Labios",
		size: "3,8 g",
		price: 11290,
		offerPrice: 7900,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152260/products/152260_1.jpg",
		featured: false
	},
	{
		id: "serum-chronos",
		name: "Sérum Antiarrugas Concentrado Chronos",
		description: "Un paso de tratamiento para sumar a tu rutina facial.",
		category: "Skincare",
		subcategory: "Tratamiento",
		size: "30 ml",
		price: 32990,
		offerPrice: 23090,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152262/products/152262_1.jpg",
		featured: true
	},
	{
		id: "limpiador-chronos",
		name: "Limpiador Purificante Antioleosidad Chronos",
		description: "Limpieza facial para comenzar y cerrar el día.",
		category: "Skincare",
		subcategory: "Limpieza",
		size: "150 g",
		price: 14290,
		offerPrice: 10000,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152264/products/152264_1.jpg",
		featured: false
	},
	{
		id: "protector-solar-facial",
		name: "Protector Solar Facial en Barra FPS 50",
		description: "Protección solar facial práctica para llevar contigo.",
		category: "Skincare",
		subcategory: "Hidratación",
		size: "50 g",
		price: 16990,
		offerPrice: 11890,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152236/products/152236_1.jpg",
		featured: true
	},
	{
		id: "crema-cereza",
		name: "Crema Corporal Tododia Cereza Negra y Praliné",
		description: "Textura cremosa y un aroma dulce para tu rutina diaria.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "400 ml",
		price: 14990,
		offerPrice: 10490,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152233/products/152233_1.jpg",
		featured: true
	},
	{
		id: "crema-manos-ekos",
		name: "Crema Hidratante para Manos Ekos Castaña",
		description: "Un cuidado nutritivo para tener siempre a mano.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "75 g",
		price: 8390,
		offerPrice: 5870,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw70983/products/70983_1.jpg",
		featured: false
	},
	{
		id: "shampoo-lumina",
		name: "Shampoo Fuerza y Reparación Molecular Lumina",
		description: "Limpieza y cuidado para sumar a tu ritual capilar.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "300 ml",
		price: 7990,
		offerPrice: 5590,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152243/products/152243_1.jpg",
		featured: false
	},
	{
		id: "chronos-acqua-repuesto",
		name: "Repuesto Acqua Biohidratante Renovador Chronos Derma",
		description: "Hidratación facial renovadora para acompañar tu rutina diaria.",
		category: "Skincare",
		subcategory: "Hidratación",
		size: "40 g",
		price: 21490,
		offerPrice: 12890,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw91849/products/91849_1.jpg",
		featured: false
	},
	{
		id: "lumina-shampoo-antioleosidad-repuesto",
		name: "Repuesto Shampoo Antioleosidad Lumina",
		description: "Limpieza capilar para ayudar a controlar el exceso de oleosidad.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "300 ml",
		price: 6490,
		offerPrice: 4020,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152235/products/152235_1.jpg",
		featured: false
	},
	{
		id: "lumina-shampoo-matizacion-repuesto",
		name: "Repuesto Shampoo Matización y Restauración Lumina",
		description: "Rutina de lavado que ayuda a matizar y restaurar el cabello.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "300 ml",
		price: 6290,
		offerPrice: 4080,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw148158/products/148158_1.jpg",
		featured: false
	},
	{
		id: "ekos-aceite-maracuya-repuesto",
		name: "Aceite Trifásico Corporal Ekos Maracuyá Repuesto",
		description: "Cuidado corporal nutritivo con la sensorialidad del maracuyá.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "200 ml",
		price: 12190,
		offerPrice: 7920,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw70984/products/70984_1.jpg",
		featured: false
	},
	{
		id: "tododia-jabon-frambuesa-repuesto",
		name: "Repuesto Jabón Líquido Corporal Frambuesa y Pimienta Rosa",
		description: "Limpieza corporal con una fragancia frutal y especiada.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "300 ml",
		price: 6690,
		offerPrice: 4010,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152241/products/152241_1.jpg",
		featured: false
	},
	{
		id: "tododia-shampoo-reparacion-repuesto",
		name: "Repuesto Shampoo Reparación Flor de Cereza y Palta Tododia",
		description: "Limpieza capilar con una fórmula enfocada en la reparación.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "300 ml",
		price: 4390,
		offerPrice: 2720,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152245/products/152245_1.jpg",
		featured: true
	},
	{
		id: "tododia-crema-cereza-repuesto",
		name: "Repuesto Crema para el Cuerpo Tododia Cereza Negra y Praliné",
		description: "Hidratación corporal diaria con aroma a cereza negra y praliné.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "400 ml",
		price: 11990,
		offerPrice: 8390,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw153387/products/153387_1.jpg",
		featured: false
	},
	{
		id: "tododia-jabon-frutas-rojas-repuesto",
		name: "Repuesto Jabón Líquido Corporal Frutas Rojas",
		description: "Jabón líquido para una limpieza corporal perfumada y práctica.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "300 ml",
		price: 6690,
		offerPrice: 4010,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152244/products/152244_1.jpg",
		featured: false
	},
	{
		id: "erva-doce-roll-on",
		name: "Desodorante Roll-on Erva Doce",
		description: "Protección desodorante con el aroma fresco de Erva Doce.",
		category: "Cuidado Personal",
		subcategory: "Desodorante",
		size: "70 ml",
		price: 8390,
		offerPrice: 5870,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw131502/products/131502_1.jpg",
		featured: false
	},
	{
		id: "ekos-manteca-castana",
		name: "Manteca Hidratante para el Cuerpo Ekos Castaña",
		description: "Textura rica para nutrir la piel y complementar el cuidado corporal.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "200 g",
		price: 17990,
		offerPrice: 12590,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw69820/products/69820_1.jpg",
		featured: false
	},
	{
		id: "lumina-protector-termico",
		name: "Protector Térmico Finalizador Lumina",
		description: "Protección térmica para acompañar el peinado y acabado del cabello.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "150 ml",
		price: 12490,
		offerPrice: 8740,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152232/products/152232_1.jpg",
		featured: false
	},
	{
		id: "kaiak-urbe-masculino",
		name: "Eau de Toilette Masculino Kaiak Urbe",
		description: "Fragancia masculina fresca para acompañar todos los días.",
		category: "Perfumería",
		subcategory: "Hombre",
		size: "100 ml",
		price: 34990,
		offerPrice: 24490,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw105511/products/105511_1.jpg",
		featured: true
	},
	{
		id: "ekos-pitanga-preta-repuesto",
		name: "Repuesto Frescor Pitanga Preta Ekos Eau de Toilette",
		description: "Frescor perfumado con notas frutales de pitanga preta.",
		category: "Perfumería",
		subcategory: "Colonias",
		size: "150 ml",
		price: 15990,
		offerPrice: 11190,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152234/products/152234_1.jpg",
		featured: false
	},
	{
		id: "tododia-body-splash-cereza-avellana",
		name: "Body Splash Tododia Cereza y Avellana",
		description: "Bruma corporal ligera con una combinación dulce y frutal.",
		category: "Perfumería",
		subcategory: "Colonias",
		size: "200 ml",
		price: 14790,
		offerPrice: 10350,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152237/products/152237_1.jpg",
		featured: false
	},
	{
		id: "tododia-body-splash-frambuesa",
		name: "Body Splash Frambuesa y Pimienta Rosa Tododia",
		description: "Aroma frutal y especiado para refrescar la piel durante el día.",
		category: "Perfumería",
		subcategory: "Colonias",
		size: "200 ml",
		price: 14790,
		offerPrice: 10350,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152238/products/152238_1.jpg",
		featured: false
	},
	{
		id: "kriska-shock",
		name: "Eau de Toilette Femenino Kriska Shock",
		description: "Fragancia femenina intensa para sumar un toque especial a tu rutina.",
		category: "Perfumería",
		subcategory: "Mujer",
		size: "100 ml",
		price: 25290,
		offerPrice: 17700,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152239/products/152239_1.jpg",
		featured: true
	},
	{
		id: "ekos-castana-frescor-repuesto",
		name: "Repuesto Frescor Castaña Ekos Eau de Toilette",
		description: "Frescor perfumado con un carácter cálido y envolvente.",
		category: "Perfumería",
		subcategory: "Colonias",
		size: "150 ml",
		price: 15990,
		offerPrice: 11190,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152240/products/152240_1.jpg",
		featured: false
	},
	{
		id: "tododia-spray-manzana-aloe",
		name: "Spray Hidratación Manzana Verde y Aloe Vera Tododia",
		description: "Spray corporal refrescante con sensación ligera e hidratante.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "200 ml",
		price: 5990,
		offerPrice: 4190,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152242/products/152242_1.jpg",
		featured: false
	},
	{
		id: "mama-bebe-aceite-embarazadas",
		name: "Aceite para Embarazadas Mamá y Bebé",
		description: "Aceite para incorporar al cuidado de la piel durante el embarazo.",
		category: "Cuidado Personal",
		subcategory: "Infantil",
		size: "200 ml",
		price: 8290,
		offerPrice: 5800,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152246/products/152246_1.jpg",
		featured: false
	},
	{
		id: "essencial-exclusivo-femenino-repuesto",
		name: "Essencial Exclusivo Femenino Repuesto",
		description: "Repuesto de fragancia femenina para renovar tu perfume favorito.",
		category: "Perfumería",
		subcategory: "Mujer",
		size: "100 ml",
		price: 34990,
		offerPrice: 24490,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152247/products/152247_1.jpg",
		featured: true
	},
	{
		id: "tododia-body-splash-ciruela-vainilla",
		name: "Body Splash Ciruela y Flor de Vainilla Tododia",
		description: "Bruma corporal con notas dulces de ciruela y flor de vainilla.",
		category: "Perfumería",
		subcategory: "Colonias",
		size: "200 ml",
		price: 14790,
		offerPrice: 10350,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152248/products/152248_1.jpg",
		featured: false
	},
	{
		id: "tododia-perfume-cabello-ciruela",
		name: "Perfume para Cabello Flor de Ciruela Tododia",
		description: "Perfume capilar para dejar una estela delicada en el cabello.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "60 ml",
		price: 8290,
		offerPrice: 5800,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152249/products/152249_1.jpg",
		featured: false
	},
	{
		id: "chronos-crema-antisenales-60-dia-repuesto",
		name: "Repuesto Crema Antiseñales Relleno Chronos 60+ Día",
		description: "Cuidado facial de día diseñado para pieles maduras.",
		category: "Skincare",
		subcategory: "Tratamiento",
		size: "60 g",
		price: 26290,
		offerPrice: 18400,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152250/products/152250_1.jpg",
		featured: false
	},
	{
		id: "tododia-jabon-manos-romero-salvia",
		name: "Jabón Líquido para Manos Romero y Salvia Tododia",
		description: "Jabón de manos con un aroma herbal de romero y salvia.",
		category: "Cuidado Personal",
		subcategory: "Cuerpo",
		size: "250 ml",
		price: 8690,
		offerPrice: 6080,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152251/products/152251_1.jpg",
		featured: false
	},
	{
		id: "erva-doce-roll-on-kit",
		name: "Kit Desodorantes Roll-on Erva Doce",
		description: "Set de tres desodorantes roll-on para tener protección de repuesto.",
		category: "Cuidado Personal",
		subcategory: "Desodorante",
		size: "3 unidades",
		price: 25170,
		offerPrice: 17610,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152252/products/152252_1.jpg",
		featured: false
	},
	{
		id: "tododia-spray-reactivador-rizos",
		name: "Spray Reactivador Cabello Rizado Tododia",
		description: "Spray para reactivar y refrescar la forma de los rizos.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "150 ml",
		price: 5990,
		offerPrice: 4190,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152253/products/152253_1.jpg",
		featured: false
	},
	{
		id: "tododia-shampoo-mora-coco",
		name: "Shampoo Hidratación Mora y Óleo de Coco Tododia",
		description: "Limpieza e hidratación capilar con mora y óleo de coco.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "300 ml",
		price: 5490,
		offerPrice: 3840,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152255/products/152255_1.jpg",
		featured: false
	},
	{
		id: "lumina-kit-cabello-danado",
		name: "Kit Tratamiento Cabellos Químicamente Dañados Lumina",
		description: "Tratamiento capilar para acompañar la recuperación del cabello dañado.",
		category: "Cuidado Personal",
		subcategory: "Cabello",
		size: "Kit",
		price: 18490,
		offerPrice: 12940,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152256/products/152256_1.jpg",
		featured: false
	},
	{
		id: "natura-una-corrector-alta-cobertura",
		name: "Corrector Alta Cobertura Natura Una",
		description: "Corrector de rostro para una cobertura precisa y uniforme.",
		category: "Maquillaje",
		subcategory: "Rostro",
		size: "10 g",
		price: 10490,
		offerPrice: 7340,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152258/products/152258_1.jpg",
		featured: false
	},
	{
		id: "natura-una-polvo-compacto-nude-me",
		name: "Polvo Compacto Nude Me Natura Una",
		description: "Polvo compacto para ayudar a sellar y matificar el maquillaje.",
		category: "Maquillaje",
		subcategory: "Rostro",
		size: "10 g",
		price: 17490,
		offerPrice: 12240,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152261/products/152261_1.jpg",
		featured: false
	},
	{
		id: "chronos-super-serum-reductor-arrugas",
		name: "Super Sérum Reductor de Arrugas Chronos",
		description: "Sérum concentrado para sumar a una rutina facial antiedad.",
		category: "Skincare",
		subcategory: "Tratamiento",
		size: "30 ml",
		price: 35490,
		offerPrice: 24840,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152263/products/152263_1.jpg",
		featured: true
	},
	{
		id: "chronos-agua-micelar",
		name: "Agua Micelar Purificante Chronos",
		description: "Limpieza facial micelar para retirar impurezas de la piel.",
		category: "Skincare",
		subcategory: "Limpieza",
		size: "150 ml",
		price: 13190,
		offerPrice: 9230,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152265/products/152265_1.jpg",
		featured: false
	},
	{
		id: "chronos-exfoliante-antisenales",
		name: "Exfoliante Antiseñales Chronos",
		description: "Exfoliante facial para complementar la renovación de la piel.",
		category: "Skincare",
		subcategory: "Limpieza",
		size: "50 g",
		price: 15990,
		offerPrice: 11190,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152266/products/152266_1.jpg",
		featured: false
	},
	{
		id: "mama-bebe-shampoo-suave",
		name: "Shampoo Suave Mamá y Bebé",
		description: "Limpieza suave para el cuidado capilar de bebés.",
		category: "Cuidado Personal",
		subcategory: "Infantil",
		size: "200 ml",
		price: 7290,
		offerPrice: 5100,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152267/products/152267_1.jpg",
		featured: false
	},
	{
		id: "mama-bebe-toallitas-humedas",
		name: "Toallitas Húmedas Limpieza Suave Mamá y Bebé",
		description: "Toallitas prácticas para una limpieza suave fuera de casa.",
		category: "Cuidado Personal",
		subcategory: "Infantil",
		size: "16 unidades",
		price: 3990,
		offerPrice: 2790,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152268/products/152268_1.jpg",
		featured: false
	},
	{
		id: "mama-bebe-colonia-sin-alcohol",
		name: "Colonia Sin Alcohol Mamá y Bebé",
		description: "Colonia delicada sin alcohol para perfumar suavemente.",
		category: "Cuidado Personal",
		subcategory: "Infantil",
		size: "100 ml",
		price: 16990,
		offerPrice: 11890,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152269/products/152269_1.jpg",
		featured: false
	},
	{
		id: "natura-homme-gel-barba",
		name: "Gel para Barba Natura Homme",
		description: "Gel de cuidado masculino para dar forma y definición a la barba.",
		category: "Cuidado Personal",
		subcategory: "Hombre",
		size: "75 g",
		price: 8990,
		offerPrice: 6290,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152270/products/152270_1.jpg",
		featured: false
	},
	{
		id: "natura-homme-balm-post-afeitado",
		name: "Balm Post Afeitado Natura Homme",
		description: "Bálsamo para cuidar e hidratar la piel después del afeitado.",
		category: "Cuidado Personal",
		subcategory: "Hombre",
		size: "75 ml",
		price: 9990,
		offerPrice: 6990,
		image: "https://production.na01.natura.com/dw/image/v2/BFKR_PRD/on/demandware.static/-/Sites-natura-cl-storefront-catalog/default/dw152271/products/152271_1.jpg",
		featured: false
	}
];
